const vendorList = [
  // Photographers (10)
  {
    category: "photographers",
    cityName: "Mumbai",
    shopName: "ShutterUp Photography",
    image: "/photographer.jpg",
    rating: 4.8,
    reviews: 120,
    price: "₹20,000 - ₹50,000",
  },
  {
    category: "photographers",
    cityName: "Delhi",
    shopName: "Candid Frames",
    image: "/photographer.jpg",
    rating: 4.9,
    reviews: 200,
    price: "₹15,000 - ₹40,000",
  },
  {
    category: "photographers",
    cityName: "Bangalore",
    shopName: "Pixel Perfection",
    image: "/photographer.jpg",
    rating: 4.7,
    reviews: 95,
    price: "₹25,000 - ₹60,000",
  },
  {
    category: "photographers",
    cityName: "Kolkata",
    shopName: "Golden Hour Studios",
    image: "/photographer.jpg",
    rating: 4.6,
    reviews: 140,
    price: "₹18,000 - ₹45,000",
  },
  {
    category: "photographers",
    cityName: "Pune",
    shopName: "Lens & Lights",
    image: "/photographer.jpg",
    rating: 4.7,
    reviews: 90,
    price: "₹22,000 - ₹55,000",
  },
  {
    category: "photographers",
    cityName: "Jaipur",
    shopName: "Royal Weddings Photography",
    image: "/photographer.jpg",
    rating: 4.8,
    reviews: 110,
    price: "₹30,000 - ₹70,000",
  },
  {
    category: "photographers",
    cityName: "Lucknow",
    shopName: "Snapshot Stories",
    image: "/photographer.jpg",
    rating: 4.5,
    reviews: 85,
    price: "₹12,000 - ₹40,000",
  },
  {
    category: "photographers",
    cityName: "Chennai",
    shopName: "Memories Studio",
    image: "/photographer.jpg",
    rating: 4.7,
    reviews: 105,
    price: "₹18,000 - ₹50,000",
  },
  {
    category: "photographers",
    cityName: "Hyderabad",
    shopName: "Dream Shutters",
    image: "/photographer.jpg",
    rating: 4.9,
    reviews: 150,
    price: "₹25,000 - ₹65,000",
  },
  {
    category: "photographers",
    cityName: "Ahmedabad",
    shopName: "Focus Point Photography",
    image: "/photographer.jpg",
    rating: 4.6,
    reviews: 98,
    price: "₹15,000 - ₹42,000",
  },

  // Caterers (10)
  {
    category: "caterers",
    cityName: "Hyderabad",
    shopName: "Royal Feast Catering",
    image: "/Catering.jpg",
    rating: 4.9,
    reviews: 150,
    price: "₹1,000 - ₹2,500 per plate",
  },
  {
    category: "caterers",
    cityName: "Chennai",
    shopName: "Delicious Delights",
    image: "/Catering.jpg",
    rating: 4.8,
    reviews: 120,
    price: "₹800 - ₹2,200 per plate",
  },
  {
    category: "caterers",
    cityName: "Mumbai",
    shopName: "Tasty Bites Catering",
    image: "/Catering.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹3,000 per plate",
  },
  {
    category: "caterers",
    cityName: "Delhi",
    shopName: "Savory Platter",
    image: "/Catering.jpg",
    rating: 4.6,
    reviews: 90,
    price: "₹1,000 - ₹2,800 per plate",
  },
  {
    category: "caterers",
    cityName: "Pune",
    shopName: "Flavors & Spices",
    image: "/Catering.jpg",
    rating: 4.5,
    reviews: 85,
    price: "₹900 - ₹2,400 per plate",
  },
  {
    category: "caterers",
    cityName: "Bangalore",
    shopName: "Eventful Eats",
    image: "/Catering.jpg",
    rating: 4.8,
    reviews: 125,
    price: "₹1,100 - ₹3,000 per plate",
  },
  {
    category: "caterers",
    cityName: "Kolkata",
    shopName: "Feast Masters",
    image: "/Catering.jpg",
    rating: 4.6,
    reviews: 98,
    price: "₹950 - ₹2,500 per plate",
  },
  {
    category: "caterers",
    cityName: "Jaipur",
    shopName: "Royal Kitchen",
    image: "/Catering.jpg",
    rating: 4.9,
    reviews: 140,
    price: "₹1,200 - ₹3,200 per plate",
  },
  {
    category: "caterers",
    cityName: "Lucknow",
    shopName: "Awadhi Cuisine Caterers",
    image: "/Catering.jpg",
    rating: 4.7,
    reviews: 105,
    price: "₹1,100 - ₹2,800 per plate",
  },
  {
    category: "caterers",
    cityName: "Ahmedabad",
    shopName: "Gourmet Catering",
    image: "/Catering.jpg",
    rating: 4.8,
    reviews: 130,
    price: "₹1,000 - ₹2,600 per plate",
  },

  // Carpenters (10)
  {
    category: "carpenters",
    cityName: "Mumbai",
    shopName: "Modern Furniture Co.",
    image: "/Carepenter.jpg",
    rating: 4.7,
    reviews: 85,
    price: "₹10,000 - ₹50,000",
  },
  {
    category: "carpenters",
    cityName: "Delhi",
    shopName: "Elite Carpentry",
    image: "/Carepenter.jpg",
    rating: 4.6,
    reviews: 90,
    price: "₹8,000 - ₹45,000",
  },
  {
    category: "carpenters",
    cityName: "Pune",
    shopName: "Woodcraft Masters",
    image: "/Carepenter.jpg",
    rating: 4.8,
    reviews: 120,
    price: "₹12,000 - ₹60,000",
  },
  {
    category: "carpenters",
    cityName: "Bangalore",
    shopName: "Timber Trends",
    image: "/Carepenter.jpg",
    rating: 4.5,
    reviews: 100,
    price: "₹10,000 - ₹50,000",
  },
  {
    category: "carpenters",
    cityName: "Bangalore",
    shopName: "Timber Trends",
    image: "/Carepenter.jpg",
    rating: 4.5,
    reviews: 100,
    price: "₹10,000 - ₹50,000",
  },
  {
    category: "carpenters",
    cityName: "Bangalore",
    shopName: "Timber Trends",
    image: "/Carepenter.jpg",
    rating: 4.5,
    reviews: 100,
    price: "₹10,000 - ₹50,000",
  },
  {
    category: "carpenters",
    cityName: "Bangalore",
    shopName: "Timber Trends",
    image: "/Carepenter.jpg",
    rating: 4.5,
    reviews: 100,
    price: "₹10,000 - ₹50,000",
  },
  {
    category: "carpenters",
    cityName: "Bangalore",
    shopName: "Timber Trends",
    image: "/Carepenter.jpg",
    rating: 4.5,
    reviews: 100,
    price: "₹10,000 - ₹50,000",
  },
  {
    category: "carpenters",
    cityName: "Bangalore",
    shopName: "Timber Trends",
    image: "/Carepenter.jpg",
    rating: 4.5,
    reviews: 100,
    price: "₹10,000 - ₹50,000",
  },
  {
    category: "carpenters",
    cityName: "Bangalore",
    shopName: "Timber Trends",
    image: "/Carepenter.jpg",
    rating: 4.5,
    reviews: 100,
    price: "₹10,000 - ₹50,000",
  },
  {
    category: "carpenters",
    cityName: "Bangalore",
    shopName: "Timber Trends",
    image: "/Carepenter.jpg",
    rating: 4.5,
    reviews: 100,
    price: "₹10,000 - ₹50,000",
  },
  // Add more entries similarly...

  // Wallpapers (10)
  {
    category: "wallpaperspecialists",
    cityName: "Bangalore",
    shopName: "Dream Decor",
    image: "/Dark1.jpg",
    rating: 4.8,
    reviews: 110,
    price: "₹1,000 - ₹5,000",
  },
  {
    category: "wallpaperspecialists",
    cityName: "Hyderabad",
    shopName: "Wall Wonders",
    image: "/Dark1.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹6,000",
  },
  {
    category: "wallpaperspecialists",
    cityName: "Hyderabad",
    shopName: "Wall Wonders",
    image: "/Dark1.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹6,000",
  },
  {
    category: "wallpaperspecialists",
    cityName: "Hyderabad",
    shopName: "Wall Wonders",
    image: "/Dark1.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹6,000",
  },
  {
    category: "wallpaperspecialists",
    cityName: "Hyderabad",
    shopName: "Wall Wonders",
    image: "/Dark1.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹6,000",
  },
  {
    category: "wallpaperspecialists",
    cityName: "Hyderabad",
    shopName: "Wall Wonders",
    image: "/Dark1.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹6,000",
  },
  {
    category: "wallpaperspecialists",
    cityName: "Hyderabad",
    shopName: "Wall Wonders",
    image: "/Dark1.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹6,000",
  },
  {
    category: "wallpaperspecialists",
    cityName: "Hyderabad",
    shopName: "Wall Wonders",
    image: "/Dark1.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹6,000",
  },
  {
    category: "wallpaperspecialists",
    cityName: "Hyderabad",
    shopName: "Wall Wonders",
    image: "/Dark1.jpg",
    rating: 4.7,
    reviews: 100,
    price: "₹1,200 - ₹6,000",
  },
  // Add more entries similarly...
];

export default vendorList;
